[package]
name = "db_receiver"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.28.0", features = ["bundled"] }
ctrlc = "3.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
